services:
  postgres:
    image: chriseaton/adventureworks:postgres
    container_name: adventureworks
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
